// enh_dur_listed_gen.h -- GENERATED by scripts/gen_enh_dur.py from Windower res/item_descriptions.lua.
// Do NOT hand-edit ; regenerate. item id -> NATIVE 'Enhancing magic duration +N%%' (from the item's
// in-game description ; negative allowed, e.g. Sroda Necklace -50). Universal / future-proof : covers
// every item in the game with a native enhancing-duration line. Augment duration is decoded from
// extdata separately (enh_dur.h). Included by enh_dur.h as the ENH_DUR_LISTED table.
#pragma once
namespace aio {
static const EnhDurItem ENH_DUR_LISTED[] = {
    {22055,10},{22097,10},{22098,15},{22099,20},{23106,20},{23134,10},{23149,8},{23178,18},{23285,25},
    {23310,5},{23357,35},{23441,25},{23469,15},{23484,12},{23513,20},{23620,30},{23645,10},{23692,40},
    {23967,15},{23982,12},{23989,20},{24074,30},{24077,10},{25444,7},{25445,8},{25446,9},{25824,20},
    {26041,-50},{26250,20},{26354,10},{26419,10},{26782,10},{26783,15},{27194,10},{27195,20},{27419,25},
    {27420,30},{27891,9},{27892,10},{27968,16},{28034,5},
};
static const int ENH_DUR_LISTED_N = (int)(sizeof(ENH_DUR_LISTED)/sizeof(ENH_DUR_LISTED[0]));
} // namespace aio
