// geo_dur_gen.h -- GENERATED by scripts/gen_geo_dur.py from Windower res/item_descriptions.lua.
// Do NOT hand-edit ; regenerate. item id -> native 'Indicolure ... duration +N' FLAT SECONDS (added to
// the Indi- base). Universal / future-proof : covers every item in the game with an Indicolure-duration
// line. Included by geo_dur.h as the GEO_DUR_LISTED table.
#pragma once
namespace aio {
struct GeoDurItem { unsigned short id; short sec; };
static const GeoDurItem GEO_DUR_LISTED[] = {
    {21085,15},{23284,18},{23373,25},{23619,21},{23708,30},{24073,21},{26266,20},{27192,12},{27193,15},
    {27451,15},{27452,20},
};
static const int GEO_DUR_LISTED_N = (int)(sizeof(GEO_DUR_LISTED)/sizeof(GEO_DUR_LISTED[0]));
} // namespace aio
