// nms_gen.h -- GENERATED by scripts/gen_nms.py from the Empy Pop Tracker NM data (vendor/nms/*.lua).
// DO NOT hand-edit ; regenerate via the script.
//
// NM pop-chain data derived from Empy Pop Tracker, (c) 2020 Dean James (Xurion of Bismarck),
// BSD 3-Clause. Full licence text : NOTICE-EmpyPop.txt (shipped alongside the plugin).
//
// The source data is a RECURSIVE tree (pops -> dropped_from -> pops -> ...). It is FLATTENED here into
// one POOL of pop entries : every entry addresses its children as an index RANGE (childFirst/childCount)
// into POPS[] itself. A sibling set is always contiguous. All static const -- zero runtime init, no heap.
//
// Ids only : resolve a name via aio::key_item_name(id) (keyitems_gen.h) when isKI, else aio::item_name(id)
// (itemnames_gen.h). Names are lowercase as they ship in res/ -- title-case at DRAW time, not here.
// `fromName` ("Adamastor, Forced (C-4)") is free text carrying the map position -- not derivable.
#pragma once

namespace aio {

// One link in a pop chain : the item/KI you need, and the mob/NPC it drops from.
// childFirst/childCount = the pops needed to force-spawn THAT mob (0 = it is a natural/timed spawn).
struct NmPop {
    unsigned short id;          // key-item id when isKI, else item id
    unsigned char  isKI;        // 1 = key item (Lua type == 'key item') ; 0 = item
    const char*    fromName;    // free text : mob/NPC + map position
    unsigned short childFirst;  // index into POPS[]
    unsigned short childCount;
};

struct Nm {
    const char*    key;         // lowercase lookup key ("briareus", "arch dynamis lord")
    const char*    en;          // display name ("Briareus")
    unsigned short collectable; // item id of the collectable, or 0 if the NM has none
    unsigned short collectableTarget; // target count, or 0
    unsigned short popFirst;    // index into POPS[]
    unsigned short popCount;
};

// The flattened pop pool. Indices are stable ; only nms_gen.h may reference them.
static const NmPop POPS[] = {
    /*   0 */ {1530, 1, "Ningishzida, Forced (I-7/I-8)", 1, 3},
    /*   1 */ {3262, 0, "Jaculus, Timed (I-8)", 0, 0},
    /*   2 */ {3261, 0, "Minaruja, Forced (I-10)", 4, 1},
    /*   3 */ {3268, 0, "Glade Wivre (I-8)", 0, 0},
    /*   4 */ {3267, 0, "Faunus Wyvern (I-9)", 0, 0},
    /*   5 */ {1532, 1, "Melo Melo, Timed (F-11/G-11)", 0, 0},
    /*   6 */ {1525, 1, "Dhorme Khimaira, Forced (F-7)", 7, 3},
    /*   7 */ {3246, 0, "Upas-Kamuy, Forced (G-5)", 10, 1},
    /*   8 */ {3247, 0, "Sisyphus, Timed (F-6/G-6)", 0, 0},
    /*   9 */ {3253, 0, "Olyphant (F-6)", 0, 0},
    /*  10 */ {3252, 0, "Snowflake (G-5)", 0, 0},
    /*  11 */ {3429, 0, "Dynamis Lord, Forced (E-8)", 16, 1},
    /*  12 */ {3430, 0, "Duke Haures, Forced (J-7)", 17, 1},
    /*  13 */ {3431, 0, "Marquis Caim, Forced (J-6)", 18, 1},
    /*  14 */ {3432, 0, "Baron Avnas, Forced (I-5)", 19, 1},
    /*  15 */ {3433, 0, "Count Haagenti, Forced (F-7)", 20, 1},
    /*  16 */ {3358, 0, "Various Demon lottery NMs", 0, 0},
    /*  17 */ {3400, 0, "Kindred DRK, RDM & SAM", 0, 0},
    /*  18 */ {3401, 0, "Kindred BRD, NIN, SMN & WAR", 0, 0},
    /*  19 */ {3402, 0, "Kindred DRG, MNK, THF & WHM", 0, 0},
    /*  20 */ {3403, 0, "Kindred BLM, BST, PLD & RNG", 0, 0},
    /*  21 */ {1531, 1, "Deelgeed, Timed (F-9/F-10)", 0, 0},
    /*  22 */ {1522, 1, "Ouzelum, Timed (I-8/J-9)", 0, 0},
    /*  23 */ {1482, 1, "Adamastor, Forced (C-4)", 26, 1},
    /*  24 */ {1484, 1, "Grandgousier, Forced (F-10)", 27, 1},
    /*  25 */ {1483, 1, "Pantagruel, Forced (F-7)", 28, 1},
    /*  26 */ {2894, 0, "Bathyal Gigas (C-5/D-5)", 0, 0},
    /*  27 */ {2896, 0, "Demersal Gigas (E-9/F-9)", 0, 0},
    /*  28 */ {2895, 0, "Hadal Gigas (F-6/F-7)", 0, 0},
    /*  29 */ {1652, 1, "Koios (Conflux #5)", 30, 1},
    /*  30 */ {1565, 1, "Fire/Earth Elemental", 31, 1},
    /*  31 */ {1564, 1, "Any Cruor Prospector", 0, 0},
    /*  32 */ {1508, 1, "Khalkotaur, Forced (F-4)", 35, 1},
    /*  33 */ {1509, 1, "Quasimodo, Forced (F-4)", 36, 1},
    /*  34 */ {1510, 1, "Lord Varney, Timed (G-10/H-10)", 0, 0},
    /*  35 */ {3098, 0, "Aestutaur (G-9/G-10)", 0, 0},
    /*  36 */ {3099, 0, "Gruesome Gargouille (F-10/G-10)", 0, 0},
    /*  37 */ {1485, 1, "La Theine Liege, Forced (I-7)", 39, 1},
    /*  38 */ {1486, 1, "Baba Yaga, Forced (H-7)", 40, 1},
    /*  39 */ {2897, 0, "Plateau Glider (H-7)", 0, 0},
    /*  40 */ {2898, 0, "Farfadet (H-7)", 0, 0},
    /*  41 */ {1470, 1, "Hedetet, Forced (F-7)", 45, 2},
    /*  42 */ {1469, 1, "Treble Noctules, Forced (I-9)", 48, 2},
    /*  43 */ {1468, 1, "Ophanim, Forced (G-9)", 51, 3},
    /*  44 */ {1471, 1, "Chukwa, Timed (F-5)", 0, 0},
    /*  45 */ {2921, 0, "Canyon Scorpion (F-7)", 0, 0},
    /*  46 */ {2948, 0, "Gancanagh, Forced (H-8)", 47, 1},
    /*  47 */ {2920, 0, "Pachypodium (H-8)", 0, 0},
    /*  48 */ {2919, 0, "Blood Bat (I-9)", 0, 0},
    /*  49 */ {2947, 0, "Cannered Noz, Forced (F-6)", 50, 1},
    /*  50 */ {2918, 0, "Caoineag (F-6)", 0, 0},
    /*  51 */ {2917, 0, "Beholder (G-9)", 0, 0},
    /*  52 */ {2946, 0, "Vetehinen, Forced (H-10)", 54, 1},
    /*  53 */ {2945, 0, "Halimede, Forced (G-12)", 55, 1},
    /*  54 */ {2916, 0, "Gulch Limule (H-10)", 0, 0},
    /*  55 */ {2915, 0, "Gully Clionid (G-12)", 0, 0},
    /*  56 */ {1504, 1, "Cep-Kamuy, Forced (F-4)", 58, 1},
    /*  57 */ {1505, 1, "Heqet, Timed (I-6)", 0, 0},
    /*  58 */ {3089, 0, "Ancient Orobon (F-5)", 0, 0},
    /*  59 */ {1521, 1, "Hazhdiha, Timed (H-10)", 0, 0},
    /*  60 */ {1473, 1, "Minhocao, Timed (I-6)", 0, 0},
    /*  61 */ {1475, 1, "Adze, Timed (G-5)", 0, 0},
    /*  62 */ {1472, 1, "Alectryon (H-8)", 64, 2},
    /*  63 */ {1474, 1, "Muscaliet, Forced (J-6)", 67, 2},
    /*  64 */ {2923, 0, "Cluckatrice (H-8)", 0, 0},
    /*  65 */ {2949, 0, "Abas, Forced (K-10)", 66, 1},
    /*  66 */ {2922, 0, "Canyon Eft (J-10/J-11)", 0, 0},
    /*  67 */ {2925, 0, "Hieracosphinx (J-6)", 0, 0},
    /*  68 */ {2950, 0, "Tefenet, Forced (G-6)", 69, 1},
    /*  69 */ {2924, 0, "Jaguarundi (G-6)", 0, 0},
    /*  70 */ {3230, 0, "Tablilla, Forced (C-11)", 72, 1},
    /*  71 */ {3236, 0, "Bonfire, (D-11/E-11)", 0, 0},
    /*  72 */ {3235, 0, "Sand Sweeper, (D-10)", 0, 0},
    /*  73 */ {3260, 0, "Teekesselchen, Forced (I-5)", 75, 1},
    /*  74 */ {3266, 0, "Stygian Djinn, (K-7)", 0, 0},
    /*  75 */ {3265, 0, "Sinister Seidel, (J-5)", 0, 0},
    /*  76 */ {3245, 0, "Koghatu, Forced (G-8)", 78, 1},
    /*  77 */ {3251, 0, "Sub-zero Gear, (F-8/F-9)", 0, 0},
    /*  78 */ {3250, 0, "Mechanical Menace, (G-8/H-8)", 0, 0},
    /*  79 */ {1526, 1, "Kur, Timed (I-5/J-5)", 0, 0},
    /*  80 */ {1488, 1, "Granite Borer, Forced (K-10)", 83, 1},
    /*  81 */ {1490, 1, "Tunga, Timed (K-10)", 0, 0},
    /*  82 */ {1489, 1, "Blazing Eruca, Forced (J-10)", 84, 1},
    /*  83 */ {3072, 0, "Gullycampa (K-10)", 0, 0},
    /*  84 */ {3073, 0, "Ignis Eruca (J-10)", 0, 0},
    /*  85 */ {1466, 1, "Arimaspi, Forced (K-6)", 88, 1},
    /*  86 */ {1464, 1, "Alkonost, Forced (H-6)", 89, 1},
    /*  87 */ {1465, 1, "Keratyrannos, Forced (G-6)", 90, 1},
    /*  88 */ {2913, 0, "Deep Eye (K-6/K-7)", 0, 0},
    /*  89 */ {2912, 0, "Ypotryll (I-7)", 0, 0},
    /*  90 */ {2910, 0, "Mesa Wivre (G-6)", 0, 0},
    /*  91 */ {1654, 1, "Gamayun (Conflux #8)", 92, 1},
    /*  92 */ {1565, 1, "Air/Dark Elemental", 93, 1},
    /*  93 */ {1564, 1, "Any Cruor Prospector", 0, 0},
    /*  94 */ {1653, 1, "Chione (Conflux #7)", 95, 1},
    /*  95 */ {1565, 1, "Ice/Water Elemental", 96, 1},
    /*  96 */ {1564, 1, "Any Cruor Prospector", 0, 0},
    /*  97 */ {1520, 1, "Amarok, Forced (E-6)", 98, 3},
    /*  98 */ {3231, 0, "Sharabha, Forced (G-5)", 101, 1},
    /*  99 */ {3232, 0, "Ansherekh, Timed (F-8/G-8)", 0, 0},
    /* 100 */ {3238, 0, "Camelopardalis (F-7/G-7)", 0, 0},
    /* 101 */ {3237, 0, "Dune Manticore (F-5/F-6)", 0, 0},
    /* 102 */ {1527, 1, "Awahondo, Timed (K-6/K-7)", 0, 0},
    /* 103 */ {1512, 1, "Hrosshvalur, Timed (J-6)", 0, 0},
    /* 104 */ {1511, 1, "Iku-Turso, Forced (J-7)", 105, 1},
    /* 105 */ {3100, 0, "Jasconius (I-7/J-7)", 0, 0},
    /* 106 */ {1500, 1, "Gukumatz, Timed (J-11)", 0, 0},
    /* 107 */ {1498, 1, "Minax Bugard, Forced (K-10)", 109, 1},
    /* 108 */ {1499, 1, "Sirrush, Forced (I-11)", 110, 1},
    /* 109 */ {3085, 0, "Abyssobugard (J-10/K-11)", 0, 0},
    /* 110 */ {3086, 0, "Dusk Lizard (J-11)", 0, 0},
    /* 111 */ {1492, 1, "Amun, Timed (H-8/I-9)", 0, 0},
    /* 112 */ {1491, 1, "Pallid Percy, Forced (J-7)", 113, 1},
    /* 113 */ {3074, 0, "Entozoon (J-7)", 0, 0},
    /* 114 */ {2986, 1, "Dremi (NPC)", 115, 10},
    /* 115 */ {2976, 1, "Warder of Temperance (Zdei, portal #1)", 0, 0},
    /* 116 */ {2977, 1, "Warder of Fortitude (Ghrah, portal #3)", 0, 0},
    /* 117 */ {2978, 1, "Warder of Faith (Euvhi, portal #12)", 0, 0},
    /* 118 */ {2979, 1, "Warder of Justice (Xzomit, portal #6)", 0, 0},
    /* 119 */ {2980, 1, "Warder of Hope (Phuabo, portal #1)", 0, 0},
    /* 120 */ {2981, 1, "Warder of Prudence (Hpemde, portal #9)", 0, 0},
    /* 121 */ {2982, 1, "Warder of Love (Yovra)", 0, 0},
    /* 122 */ {2983, 1, "Warder of Dignity (Limule, portal #4)", 0, 0},
    /* 123 */ {2984, 1, "Warder of Loyalty (Clionid, portal #13)", 0, 0},
    /* 124 */ {2985, 1, "Warder of Mercy (Murex, portal #7)", 0, 0},
};
static const int POPS_N = 125;

// Sorted by key (binary-searched) -- also the stable order the config row_selector iterates.
static const Nm NMS[] = {
    {"alfard", "Alfard", 3291, 75, 0, 1},
    {"amphitrite", "Amphitrite", 0, 0, 5, 1},
    {"apademak", "Apademak", 3289, 75, 6, 1},
    {"arch dynamis lord", "Arch Dynamis Lord", 0, 0, 11, 5},
    {"azdaja", "Azdaja", 3292, 75, 21, 1},
    {"bennu", "Bennu", 0, 0, 22, 1},
    {"briareus", "Briareus", 2929, 50, 23, 3},
    {"brulo", "Brulo", 3294, 75, 29, 1},
    {"bukhis", "Bukhis", 2966, 50, 32, 3},
    {"carabosse", "Carabosse", 2930, 50, 37, 2},
    {"chloris", "Chloris", 2928, 50, 41, 4},
    {"cirein-croin", "Cirein-croin", 2965, 50, 56, 2},
    {"dragua", "Dragua", 3288, 75, 59, 1},
    {"glavoid", "Glavoid", 2927, 50, 60, 4},
    {"ironclad smiter", "Ironclad Smiter", 3293, 50, 70, 2},
    {"ironclad sunderer", "Ironclad Sunderer", 3293, 50, 73, 2},
    {"ironclad triturator", "Ironclad Triturator", 3293, 50, 76, 2},
    {"isgebind", "Isgebind", 3290, 75, 79, 1},
    {"itzpapalotl", "Itzpapalotl", 2962, 50, 80, 3},
    {"kukulkan", "Kukulkan", 2932, 50, 85, 3},
    {"maere", "Maere", 3294, 75, 91, 1},
    {"ogopogo", "Ogopogo", 3294, 75, 94, 1},
    {"orthrus", "Orthrus", 3287, 75, 97, 1},
    {"resheph", "Resheph", 0, 0, 102, 1},
    {"sedna", "Sedna", 2967, 50, 103, 2},
    {"sobek", "Sobek", 2964, 50, 106, 3},
    {"ulhuadshi", "Ulhuadshi", 2963, 50, 111, 2},
    {"warder of courage", "Warder of Courage", 0, 0, 114, 1},
};
static const int NMS_N = 28;

// Case-sensitive lookup by lowercase key ("briareus"), or 0 if unknown.
inline const Nm* nm_by_key(const char* key) {
    if (!key) return 0;
    int lo = 0, hi = NMS_N - 1;
    while (lo <= hi) { const int mid = (lo + hi) >> 1;
        const char* a = NMS[mid].key; const char* b = key;
        while (*a && *a == *b) { ++a; ++b; }
        const int c = (int)(unsigned char)*a - (int)(unsigned char)*b;
        if (c == 0) return &NMS[mid]; if (c < 0) lo = mid + 1; else hi = mid - 1; }
    return 0;
}

} // namespace aio
