// song_family_gen.h -- GENERATED by scripts/gen_song_family.py from Windower res/spells.lua.
// BRD song spell id -> Timers song-family id (1 Paeon .. 15 Operetta ; 11 Hymnus 12 Mazurka 14 Scherzo).
// Do NOT hand-edit ; regenerate. Used by song_dur.h for per-family gear bonuses + the m3 term.
#pragma once
namespace aio {
struct SongFamily { unsigned short spell; unsigned char family; };
static const SongFamily SONG_FAMILY[] = {
    {378,1},{379,1},{380,1},{381,1},{382,1},{383,1},{384,1},{385,1},{386,2},{387,2},{388,2},{389,3},{390,3},
    {391,3},{392,3},{393,3},{394,4},{395,4},{396,4},{397,4},{398,4},{399,5},{400,5},{401,6},{402,6},{403,7},
    {404,7},{405,15},{406,15},{408,15},{409,15},{410,15},{411,15},{412,15},{414,15},{417,8},{419,8},{420,8},
    {424,9},{425,9},{426,9},{427,9},{428,9},{429,9},{430,9},{431,9},{432,9},{433,9},{434,9},{435,9},{436,9},
    {437,9},{438,10},{439,10},{440,10},{441,10},{442,10},{443,10},{444,10},{445,10},{446,10},{447,10},
    {448,10},{449,10},{450,10},{451,10},{452,10},{453,10},{464,11},{465,12},{467,12},{468,13},{469,13},
    {470,14},
};
static const int SONG_FAMILY_N = (int)(sizeof(SONG_FAMILY)/sizeof(SONG_FAMILY[0]));
// spell id -> family (0 = not a family-mapped buff song).
inline int song_family(unsigned spell) {
    int lo = 0, hi = SONG_FAMILY_N - 1;
    while (lo <= hi) { int mid = (lo + hi) >> 1; unsigned s = SONG_FAMILY[mid].spell;
        if (s == spell) return SONG_FAMILY[mid].family; if (s < spell) lo = mid + 1; else hi = mid - 1; }
    return 0;
}
} // namespace aio
