// weapon_skills_gen.h -- AUTO-GENERATED from Windower res/weapon_skills.lua (do not edit).
// Regenerate: python scripts/gen_ws.py
#pragma once
#include "gfx/d3d.h"

namespace aio {

struct WSRow { unsigned id; const char* en; };
static const WSRow WEAPON_SKILLS[] = {
    {1, "Combo"},
    {2, "Shoulder Tackle"},
    {3, "One Inch Punch"},
    {4, "Backhand Blow"},
    {5, "Raging Fists"},
    {6, "Spinning Attack"},
    {7, "Howling Fist"},
    {8, "Dragon Kick"},
    {9, "Asuran Fists"},
    {10, "Final Heaven"},
    {11, "Ascetic's Fury"},
    {12, "Stringing Pummel"},
    {13, "Tornado Kick"},
    {14, "Victory Smite"},
    {15, "Shijin Spiral"},
    {16, "Wasp Sting"},
    {17, "Viper Bite"},
    {18, "Shadowstitch"},
    {19, "Gust Slash"},
    {20, "Cyclone"},
    {21, "Energy Steal"},
    {22, "Energy Drain"},
    {23, "Dancing Edge"},
    {24, "Shark Bite"},
    {25, "Evisceration"},
    {26, "Mercy Stroke"},
    {27, "Mandalic Stab"},
    {28, "Mordant Rime"},
    {29, "Pyrrhic Kleos"},
    {30, "Aeolian Edge"},
    {31, "Rudra's Storm"},
    {32, "Fast Blade"},
    {33, "Burning Blade"},
    {34, "Red Lotus Blade"},
    {35, "Flat Blade"},
    {36, "Shining Blade"},
    {37, "Seraph Blade"},
    {38, "Circle Blade"},
    {39, "Spirits Within"},
    {40, "Vorpal Blade"},
    {41, "Swift Blade"},
    {42, "Savage Blade"},
    {43, "Knights of Round"},
    {44, "Death Blossom"},
    {45, "Atonement"},
    {46, "Expiacion"},
    {47, "Sanguine Blade"},
    {48, "Hard Slash"},
    {49, "Power Slash"},
    {50, "Frostbite"},
    {51, "Freezebite"},
    {52, "Shockwave"},
    {53, "Crescent Moon"},
    {54, "Sickle Moon"},
    {55, "Spinning Slash"},
    {56, "Ground Strike"},
    {57, "Scourge"},
    {58, "Herculean Slash"},
    {59, "Torcleaver"},
    {60, "Resolution"},
    {61, "Dimidiation"},
    {62, "Fimbulvetr"},
    {64, "Raging Axe"},
    {65, "Smash Axe"},
    {66, "Gale Axe"},
    {67, "Avalanche Axe"},
    {68, "Spinning Axe"},
    {69, "Rampage"},
    {70, "Calamity"},
    {71, "Mistral Axe"},
    {72, "Decimation"},
    {73, "Onslaught"},
    {74, "Primal Rend"},
    {75, "Bora Axe"},
    {76, "Cloudsplitter"},
    {77, "Ruinator"},
    {78, "Blitz"},
    {80, "Shield Break"},
    {81, "Iron Tempest"},
    {82, "Sturmwind"},
    {83, "Armor Break"},
    {84, "Keen Edge"},
    {85, "Weapon Break"},
    {86, "Raging Rush"},
    {87, "Full Break"},
    {88, "Steel Cyclone"},
    {89, "Metatron Torment"},
    {90, "King's Justice"},
    {91, "Fell Cleave"},
    {92, "Ukko's Fury"},
    {93, "Upheaval"},
    {94, "Disaster"},
    {96, "Slice"},
    {97, "Dark Harvest"},
    {98, "Shadow of Death"},
    {99, "Nightmare Scythe"},
    {100, "Spinning Scythe"},
    {101, "Vorpal Scythe"},
    {102, "Guillotine"},
    {103, "Cross Reaper"},
    {104, "Spiral Hell"},
    {105, "Catastrophe"},
    {106, "Insurgency"},
    {107, "Infernal Scythe"},
    {108, "Quietus"},
    {109, "Entropy"},
    {110, "Origin"},
    {112, "Double Thrust"},
    {113, "Thunder Thrust"},
    {114, "Raiden Thrust"},
    {115, "Leg Sweep"},
    {116, "Penta Thrust"},
    {117, "Vorpal Thrust"},
    {118, "Skewer"},
    {119, "Wheeling Thrust"},
    {120, "Impulse Drive"},
    {121, "Geirskogul"},
    {122, "Drakesbane"},
    {123, "Sonic Thrust"},
    {124, "Camlann's Torment"},
    {125, "Stardiver"},
    {126, "Diarmuid"},
    {128, "Blade: Rin"},
    {129, "Blade: Retsu"},
    {130, "Blade: Teki"},
    {131, "Blade: To"},
    {132, "Blade: Chi"},
    {133, "Blade: Ei"},
    {134, "Blade: Jin"},
    {135, "Blade: Ten"},
    {136, "Blade: Ku"},
    {137, "Blade: Metsu"},
    {138, "Blade: Kamu"},
    {139, "Blade: Yu"},
    {140, "Blade: Hi"},
    {141, "Blade: Shun"},
    {142, "Zesho Meppo"},
    {144, "Tachi: Enpi"},
    {145, "Tachi: Hobaku"},
    {146, "Tachi: Goten"},
    {147, "Tachi: Kagero"},
    {148, "Tachi: Jinpu"},
    {149, "Tachi: Koki"},
    {150, "Tachi: Yukikaze"},
    {151, "Tachi: Gekko"},
    {152, "Tachi: Kasha"},
    {153, "Tachi: Kaiten"},
    {154, "Tachi: Rana"},
    {155, "Tachi: Ageha"},
    {156, "Tachi: Fudo"},
    {157, "Tachi: Shoha"},
    {158, "Tachi: Suikawari"},
    {159, "Tachi: Mumei"},
    {160, "Shining Strike"},
    {161, "Seraph Strike"},
    {162, "Brainshaker"},
    {163, "Starlight"},
    {164, "Moonlight"},
    {165, "Skullbreaker"},
    {166, "True Strike"},
    {167, "Judgment"},
    {168, "Hexa Strike"},
    {169, "Black Halo"},
    {170, "Randgrith"},
    {171, "Mystic Boon"},
    {172, "Flash Nova"},
    {173, "Dagan"},
    {174, "Realmrazer"},
    {175, "Exudation"},
    {176, "Heavy Swing"},
    {177, "Rock Crusher"},
    {178, "Earth Crusher"},
    {179, "Starburst"},
    {180, "Sunburst"},
    {181, "Shell Crusher"},
    {182, "Full Swing"},
    {183, "Spirit Taker"},
    {184, "Retribution"},
    {185, "Gate of Tartarus"},
    {186, "Vidohunir"},
    {187, "Garland of Bliss"},
    {188, "Omniscience"},
    {189, "Cataclysm"},
    {190, "Myrkr"},
    {191, "Shattersoul"},
    {192, "Flaming Arrow"},
    {193, "Piercing Arrow"},
    {194, "Dulling Arrow"},
    {196, "Sidewinder"},
    {197, "Blast Arrow"},
    {198, "Arching Arrow"},
    {199, "Empyreal Arrow"},
    {200, "Namas Arrow"},
    {201, "Refulgent Arrow"},
    {202, "Jishnu's Radiance"},
    {203, "Apex Arrow"},
    {204, "Sarv"},
    {208, "Hot Shot"},
    {209, "Split Shot"},
    {210, "Sniper Shot"},
    {212, "Slug Shot"},
    {213, "Blast Shot"},
    {214, "Heavy Shot"},
    {215, "Detonator"},
    {216, "Coronach"},
    {217, "Trueflight"},
    {218, "Leaden Salute"},
    {219, "Numbing Shot"},
    {220, "Wildfire"},
    {221, "Last Stand"},
    {222, "Terminus"},
    {224, "Exenterator"},
    {225, "Chant du Cygne"},
    {226, "Requiescat"},
    {227, "Knights of Rotund"},
    {228, "Final Paradise"},
    {229, "Fast Blade II"},
    {230, "Dragon Blow"},
    {231, "Maru Kala"},
    {232, "Ruthless Stroke"},
    {233, "Imperator"},
    {234, "Dagda"},
    {235, "Oshala"},
    {238, "Uriel Blade"},
    {239, "Glory Slash"},
    {240, "Tartarus Torpor"},
    {241, "Netherspikes"},
    {242, "Carnal Nightmare"},
    {243, "Aegis Schism"},
    {244, "Dancing Chains"},
    {245, "Barbed Crescent"},
    {246, "Shackled Fists"},
    {247, "Foxfire"},
    {248, "Grim Halo"},
    {249, "Netherspikes"},
    {250, "Carnal Nightmare"},
    {251, "Aegis Schism"},
    {252, "Dancing Chains"},
    {253, "Barbed Crescent"},
    {254, "Vulcan Shot"},
    {255, "Dimensional Death"},
};
static const int WEAPON_SKILLS_N = 241;

inline const WSRow* ws_info(unsigned id) {
    int lo = 0, hi = WEAPON_SKILLS_N - 1;
    while (lo <= hi) { int mid = (lo + hi) >> 1;
        if (WEAPON_SKILLS[mid].id == id) return &WEAPON_SKILLS[mid];
        if (WEAPON_SKILLS[mid].id < id) lo = mid + 1; else hi = mid - 1; }
    return 0;
}

} // namespace aio
