#!/usr/bin/env python3
# gen_recast_icons.py -- map a RECAST id -> the action icon_id, for the Timers box's recast column.
#
# The client recast tables give a recast_id (job abilities : byte[0] of g+0x230 ; spells : the g+0x234 array index).
# Name resolution scans the GENERATED tables (abilities_gen.h / spells_gen.h) by their recast_id field, so the icon
# table MUST use the SAME recast_id space or icons fall back to names. We therefore JOIN, keyed by the action id:
#   gen table  (id -> recast_id)   [abilities_gen.h / spells_gen.h : recast_id is the LAST numeric field of a row]
#   res table  (id -> icon_id)     [res/job_abilities.lua / res/spells.lua]
# -> recast_id -> icon_id (first id wins for a shared recast_id). icon_id indexes assets/action_icons.raw
#    (cell = icon_id%32, icon_id/32).
#
# Output : src/model/recast_icons_gen.h  (two sorted {recast_id, icon_id} tables + binary-search accessors).
import re, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TB   = os.path.join(ROOT, '..', '..', 'addons', 'AioHUD', 'vendor', 'targetbar')   # tb_abilities / tb_spells
OUT  = os.path.join(ROOT, 'src', 'model', 'recast_icons_gen.h')

def gen_recast(path):                                   # id -> recast_id  (recast_id = the LAST number in a gen row)
    m = {}
    with open(path, 'r', encoding='utf-8') as f:
        for line in f:
            mt = re.match(r'\s*\{(\d+),\s*"[^"]*",\s*(.+)\}', line)
            if not mt: continue
            nums = re.findall(r'\d+', mt.group(2))
            if nums: m[int(mt.group(1))] = int(nums[-1])
    return m

def tb_icon(path):                                      # action id -> icon index into assets/icons/ (1st num in {n, dur})
    m = {}                                              # targetbar's curated numbering that action_icons.raw is baked from
    with open(path, 'r', encoding='utf-8') as f:
        for line in f:
            mt = re.match(r'\s*\[\s*(\d+)\s*\]\s*=\s*\{\s*(\d+)', line)
            if mt: m[int(mt.group(1))] = int(mt.group(2))
    return m

def join(id2recast, id2icon):                           # recast_id -> icon index (first action id wins for a shared recast)
    m = {}
    for sid, rid in sorted(id2recast.items()):
        if rid > 0 and rid < 0x400 and sid in id2icon and rid not in m:
            m[rid] = id2icon[sid]
    return sorted(m.items())

ja = join(gen_recast(os.path.join(ROOT, 'src', 'model', 'abilities_gen.h')), tb_icon(os.path.join(TB, 'tb_abilities.lua')))
sp = join(gen_recast(os.path.join(ROOT, 'src', 'model', 'spells_gen.h')),    tb_icon(os.path.join(TB, 'tb_spells.lua')))

def emit(name, rows):
    out = ['static const RcIcon %s[] = {' % name]
    out += ['    {%d,%d},' % (r, i) for r, i in rows]
    out.append('};')
    out.append('static const int %s_N = %d;' % (name, len(rows)))
    return out

L = []
L.append('// recast_icons_gen.h -- GENERATED by scripts/gen_recast_icons.py.')
L.append('// recast_id -> icon index, joined from {abilities_gen,spells_gen}.h (id->recast_id) + tb_{abilities,spells}.lua (id->icon).')
L.append('// the icon index is targetbar\'s curated assets/icons/ numbering (gen_action_icons.py) -> cell = idx%32, idx/32.')
L.append('#pragma once')
L.append('namespace aio {')
L.append('struct RcIcon { unsigned short recast_id, icon_id; };')
L += emit('JA_RC_ICON', ja)
L += emit('SP_RC_ICON', sp)
L.append('inline unsigned rc_icon_lookup(const RcIcon* a, int n, unsigned rid) {')
L.append('    int lo = 0, hi = n - 1;')
L.append('    while (lo <= hi) { int mid = (lo + hi) >> 1; unsigned m = a[mid].recast_id;')
L.append('        if (m == rid) return a[mid].icon_id; if (m < rid) lo = mid + 1; else hi = mid - 1; }')
L.append('    return 0; }')
L.append('inline unsigned ja_recast_icon(unsigned rid)    { return rc_icon_lookup(JA_RC_ICON, JA_RC_ICON_N, rid); }')
L.append('inline unsigned spell_recast_icon(unsigned rid) { return rc_icon_lookup(SP_RC_ICON, SP_RC_ICON_N, rid); }')
L.append('} // namespace aio')

with open(OUT, 'w', encoding='utf-8') as f:
    f.write('\n'.join(L) + '\n')
print('wrote %s : %d JA + %d spell recast->icon rows' % (OUT, len(ja), len(sp)))
