#!/usr/bin/env python3
# gen_skillchain.py -- generate src/model/skillchain_gen.h from the reference SkillChains data
# (addons/AioHUD/data/tables/skills.lua, Ivaar). Emits, per resource (weapon_skills / spells /
# monster_abilities / job_abilities / elements), a sorted id -> { up to 3 skillchain PROPERTY indices,
# delay, aeonic-property index } table + a binary-search lookup. Names are NOT emitted (resolved via the
# plugin's existing ws_info / spell_info / mobskill_info at display time). Property indices match the
# SCProp enum in src/model/skillchain.h -- keep the two in sync.
#
# Run:  python scripts/gen_skillchain.py   (from the repo root)
import re, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LUA  = os.path.join(ROOT, '..', '..', 'addons', 'AioHUD', 'data', 'tables', 'skills.lua')
OUT  = os.path.join(ROOT, 'src', 'model', 'skillchain_gen.h')

# SCProp enum order -- MUST match src/model/skillchain.h.
PROPS = ['Transfixion','Compression','Liquefaction','Scission','Reverberation','Detonation',
         'Impaction','Induration','Gravitation','Fragmentation','Distortion','Fusion',
         'Light','Darkness','Radiance','Umbra']
PROP_IX = {p: i for i, p in enumerate(PROPS)}

RESOURCES = ['weapon_skills', 'spells', 'monster_abilities', 'job_abilities', 'elements']

def parse_resource(text, name):
    # isolate  skills.<name> = { ... }  up to the next  skills.<other> =  or  return skills
    m = re.search(r'skills\.' + name + r'\s*=\s*\{', text)
    if not m:
        sys.exit('resource not found: ' + name)
    start = m.end()
    depth, i = 1, start
    while i < len(text) and depth > 0:
        c = text[i]
        if c == '{': depth += 1
        elif c == '}': depth -= 1
        i += 1
    body = text[start:i-1]
    rows = []
    # [id] = { en = '...', skillchain = { 'A', 'B' }, [delay = N,] [aeonic = 'X',] ... }
    # BALANCE the entry's braces (its skillchain={...} is a nested table) -> a naive '.*?}' would stop at the
    # skillchain's closing brace and drop every entry that has fields AFTER the skillchain (aeonic/weapon/delay).
    for em in re.finditer(r'\[(-?\d+)\]\s*=\s*\{', body):
        eid = int(em.group(1)); j = em.end(); d = 1
        while j < len(body) and d > 0:
            c = body[j]
            if c == '{': d += 1
            elif c == '}': d -= 1
            j += 1
        fields = body[em.end():j-1]
        sc = re.search(r'skillchain\s*=\s*\{([^}]*)\}', fields)
        if not sc:
            continue
        props = re.findall(r"'([^']+)'", sc.group(1))
        ix = []
        for p in props:
            if p not in PROP_IX:
                sys.exit('unknown skillchain property %r (id %d, %s)' % (p, eid, name))
            ix.append(PROP_IX[p])
        if not ix:
            continue
        ix = (ix + [255, 255, 255])[:3]                       # pad to 3 (255 = none)
        d = re.search(r'delay\s*=\s*(\d+)', fields)
        delay = int(d.group(1)) if d else 3
        ae = re.search(r"aeonic\s*=\s*'([^']+)'", fields)
        aeonic = PROP_IX[ae.group(1)] if ae and ae.group(1) in PROP_IX else 255
        nm = re.search(r"en\s*=\s*'([^']*)'", fields)
        rows.append((eid, ix[0], ix[1], ix[2], delay, aeonic, nm.group(1) if nm else ''))
    rows.sort(key=lambda r: r[0])
    return rows

def main():
    with open(LUA, 'r', encoding='utf-8', errors='replace') as f:
        text = f.read()
    out = []
    out.append('// skillchain_gen.h -- GENERATED by scripts/gen_skillchain.py from the reference SkillChains')
    out.append('// data (skills.lua, Ivaar). DO NOT hand-edit ; regenerate via the script. One row per action')
    out.append('// that has skillchain properties : id -> up to 3 SCProp indices (255 = none) + delay(s) + aeonic.')
    out.append('#pragma once')
    out.append('#include "model/skillchain.h"   // SCProp enum + SkillRow')
    out.append('')
    out.append('namespace aio {')
    out.append('')
    res_rows = {r: parse_resource(text, r) for r in RESOURCES}

    # AUGMENT job_abilities : the skillchaining PET Ready moves the client exposes via get_abilities().job_abilities
    # use the ability-resource id namespace (e.g. Mega Scissors = 789), while the source addon's job_abilities table
    # was only a 75-entry subset. Cross-reference every ability in the plugin's abilities_gen.h by NAME against a
    # skillchaining monster_ability (same move, different id namespace) and add the missing ones -> FULL pet-move
    # prediction coverage (better than the reference addon), keyed by the Ready-menu id read at runtime.
    mob_by_name = {}
    for row in res_rows['monster_abilities']:
        nm = (row[6] or '').lower()
        if nm and nm not in mob_by_name:
            mob_by_name[nm] = row
    ja_ids = set(r[0] for r in res_rows['job_abilities'])
    abil_h = os.path.join(ROOT, 'src', 'model', 'abilities_gen.h')
    added = 0
    if os.path.exists(abil_h):
        atext = open(abil_h, encoding='utf-8', errors='replace').read()
        for m in re.finditer(r'\{\s*(\d+)\s*,\s*"([^"]*)"\s*,', atext):
            aid = int(m.group(1)); anm = m.group(2).lower()
            if aid in ja_ids or aid > 1023:                      # already mapped / out of the JA bitmask range
                continue
            mob = mob_by_name.get(anm)
            if mob:
                res_rows['job_abilities'].append((aid, mob[1], mob[2], mob[3], mob[4], 255, m.group(2)))
                ja_ids.add(aid); added += 1
        res_rows['job_abilities'].sort(key=lambda r: r[0])
    print('[gen_skillchain] augmented job_abilities with %d name-matched pet ready moves' % added)

    total = 0
    for r in RESOURCES:
        rows = res_rows[r]
        total += len(rows)
        out.append('// %s : %d entries' % (r, len(rows)))
        out.append('static const SkillRow SC_%s[] = {' % r.upper())
        for row in rows:
            out.append('    {%d, {%d,%d,%d}, %d, %d},' % (row[0], row[1], row[2], row[3], row[4], row[5]))
        out.append('};')
        out.append('static const int SC_%s_N = %d;' % (r.upper(), len(rows)))
        out.append('')
    out.append('} // namespace aio')
    out.append('')
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(out))
    print('[gen_skillchain] %d rows across %d resources -> %s' % (total, len(RESOURCES), OUT))

if __name__ == '__main__':
    main()
