#!/usr/bin/env python3
# gen_itemnames.py -- generate src/model/itemnames_gen.h from Windower's res/items.lua.
# The Treasure Pool (and any item-label feature) needs id -> English name. res/items.lua is ~5 MB / ~23.5k
# items ; we keep ONLY (id, en), sorted by id for a binary-search lookup. DO NOT hand-edit the output.
#
# Run:  python scripts/gen_itemnames.py   (from the repo root)
import re, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LUA  = os.path.join(ROOT, '..', '..', 'res', 'items.lua')
OUT  = os.path.join(ROOT, 'src', 'model', 'itemnames_gen.h')

def cstr(s):
    # Work on UTF-8 BYTES so a multi-byte char keeps its exact bytes (the font's utf8_next decodes 2-byte
    # sequences to Latin-1). A hex escape (\xNN) is followed by "" so the compiler can't greedily merge it with
    # a following hex digit ("\x6a" + "1" would become \x6a1 = out of range) -- the empty string breaks parsing.
    out = []
    for by in s.encode('utf-8'):
        if   by == 0x5C: out.append('\\\\')          # backslash
        elif by == 0x22: out.append('\\"')           # quote
        elif 32 <= by < 127: out.append(chr(by))
        else: out.append('\\x%02x""' % by)           # non-ASCII / control byte : escape + string-break
    return ''.join(out)

def main():
    with open(LUA, 'r', encoding='utf-8', errors='replace') as f:
        text = f.read()
    rows = []
    seen = set()
    # [id] = {id=N,en="NAME",ja=...}
    for m in re.finditer(r'\[(\d+)\]\s*=\s*\{[^}]*?\ben\s*=\s*"((?:[^"\\]|\\.)*)"', text):
        iid = int(m.group(1))
        if iid < 0 or iid > 65535 or iid in seen:
            continue
        name = m.group(2)
        if not name or name == '.':      # skip placeholders / blanks
            continue
        seen.add(iid)
        rows.append((iid, name))
    rows.sort(key=lambda r: r[0])

    out = []
    out.append('// itemnames_gen.h -- GENERATED by scripts/gen_itemnames.py from Windower res/items.lua.')
    out.append('// id -> English item name (sorted by id, binary-searched). DO NOT hand-edit ; regenerate via the script.')
    out.append('#pragma once')
    out.append('')
    out.append('namespace aio {')
    out.append('')
    out.append('struct ItemNameRow { unsigned short id; const char* en; };')
    out.append('static const ItemNameRow ITEM_NAMES[] = {')
    for (iid, name) in rows:
        out.append('    {%d, "%s"},' % (iid, cstr(name)))
    out.append('};')
    out.append('static const int ITEM_NAMES_N = %d;' % len(rows))
    out.append('')
    out.append('// English name for an item id, or 0 if unknown.')
    out.append('inline const char* item_name(unsigned id) {')
    out.append('    int lo = 0, hi = ITEM_NAMES_N - 1;')
    out.append('    while (lo <= hi) { const int mid = (lo + hi) >> 1; const unsigned m = ITEM_NAMES[mid].id;')
    out.append('        if (m == id) return ITEM_NAMES[mid].en; if (m < id) lo = mid + 1; else hi = mid - 1; }')
    out.append('    return 0;')
    out.append('}')
    out.append('')
    out.append('} // namespace aio')
    out.append('')
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(out))
    print('[gen_itemnames] %d items -> %s' % (len(rows), OUT))

if __name__ == '__main__':
    main()
